"""
Django settings for django project.

Generated by 'django-admin startproject'.

For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_flag(name, default="False"):
    """Lee booleanos desde variables de entorno de forma tolerante.

    Acepta: "1", "true", "yes", "on" (case-insensitive) -> True
    """
    raw = os.environ.get(name, default)
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    """Lee listas separadas por comas desde variables de entorno."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# ---------------------------------------------------------------------------
# Core / Seguridad
# ---------------------------------------------------------------------------

# SECURITY WARNING: don't run with debug turned on in production!
# OJO: antes estaba `== "False"`, lo cual invertia la logica y activaba DEBUG
# cuando el usuario seteaba DJANGO_DEBUG=False (justo lo contrario de lo deseado).
DEBUG = env_flag("DJANGO_DEBUG", default="False")

# SECRET_KEY: si no viene del entorno se genera una aleatoria para que el
# contenedor siempre levante. OJO: al ser aleatoria cambia en cada redespliegue,
# lo que invalida las sesiones abiertas. Define DJANGO_SECRET_KEY en Seenode
# para que sea estable.
_secret_from_env = os.environ.get("DJANGO_SECRET_KEY")

if _secret_from_env:
    SECRET_KEY = _secret_from_env
else:
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY = get_random_secret_key()
    import warnings

    warnings.warn(
        "DJANGO_SECRET_KEY no esta definida: se genero una clave aleatoria. "
        "Las sesiones se invalidan en cada reinicio/despliegue. Define "
        "DJANGO_SECRET_KEY en las variables de entorno de Seenode.",
        RuntimeWarning,
        stacklevel=2,
    )

# Acepta cualquier host por defecto; se puede restringir con DJANGO_ALLOWED_HOSTS.
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "*") or ["*"]

# Dominios https desde los que Django acepta formularios (login/signup).
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Seenode pone un proxy inverso delante: Django debe leer el protocolo real de
# los headers, si no `request.is_secure()` devuelve False y CSRF/reirects fallan.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if env_flag("DJANGO_SECURE_SSL_REDIRECT", default="False"):
    SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "example",
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # whitenoise: sirve /static/ directamente desde la app (sin nginx, sin volumen extra)
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DJANGO_SQLITE_PATH", BASE_DIR / "db.sqlite3"),
        "OPTIONS": {
            # timeout evita "database is locked" cuando gunicorn corre varios workers
            "timeout": 20,
            # WAL permite lecturas y escrituras simultaneas en sqlite
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# whitenoise sirve los archivos estaticos comprimidos y con cache desde el propio
# contenedor. Sin esto, con DEBUG=False Django NO sirve /static/ y la pagina sale
# sin estilos (y los .css darian 404).
#
# El backend con manifiesto (hash en el nombre) es el ideal, pero si collectstatic
# no llego a ejecutarse, {% static %} revienta con
# "ValueError: Missing staticfiles manifest entry" y TODAS las paginas dan 500.
# Por eso se elige en runtime segun exista el manifiesto: si falta, se cae al
# backend sin manifiesto y el sitio sigue sirviendo (solo sin hash de cache).
_manifest_exists = (Path(STATIC_ROOT) / "staticfiles.json").is_file()

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if _manifest_exists
            else "whitenoise.storage.CompressedStaticFilesStorage"
        )
    },
}
